backend:
  name: github
  repo: ralf-test-netlify/test-netlify # Path to your Github repository
  branch: master # Branch to update

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "json"
    label: "Json"
    folder: "_data/json"
    create: "true"
    slug: "{{id}}-{{version}}"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Version", name: "version", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Json", name: "json", widget: "ace", default: "{}"}

  - name: "video"
    label: "Video"
    folder: "_data/video"
    create: "true"
    slug: "{{videoId}}-{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "video"}
      - {label: "DisplayName", name: "displayName", widget: "string"}
      - {label: "VideoId", name: "videoId", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Duration", name: "duration", widget: "number"}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "text-event"
    label: "TextEvent"
    folder: "_data/event"
    create: true
    slug: "{{videoId}}-{{time}}-{{type}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "textEvent"}
      - {label: "VideoId", name: "videoId", widget: "string"}
      - {label: "Time", name: "time", widget: "number"}
      - {label: "Duration", name: "duration", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"} # Body is a special name, it is shown as the main markdown content

  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}