backend:
  name: github
  repo: ralf-test-netlify/test-netlify # Path to your Github repository
  branch: master # Branch to update

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "json"
    label: "Json"
    folder: "_data/json"
    create: "true"
    slug: "{{id}}-{{version}}"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Version", name: "version", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Json", name: "json", widget: "ace", default: "{}"}
